# Generated by Django 4.2.7 on 2023-11-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballVisionApp', '0003_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfile',
            name='email',
        ),
    ]
