# Generated by Django 4.2.7 on 2023-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballVisionApp', '0004_remove_inputfile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=32, unique=True),
        ),
    ]
